### PR TITLE
Drop the 'os' and 'ver' from the configuration file. Related to #46

### PR DESCRIPTION
**Pull request by sayanchowdhury**

### CODE REVIEW

**Comment by pypingou** [comment]
Looks fine to me but I don't know what is the idea here.

**Comment by sayanchowdhury** [comment]
I have synced the config file with the file in the infra ansible repo. Right now we maintain both the configuration https://github.com/nishant-mor/fedimg/blob/05452ed71e595aad31cebf09497fbb251eed1550/fedimg/services/ec2.py#L98, so it's better if we drop the old configuration.

**Comment by pypingou** [comment]
Hm now the patch seems unrelated to the title of the PR :(

**Comment by pypingou** [comment]
:+1: for me

**Comment by sayanchowdhury** [comment]
Thanks :)

**Pull request merged**
