### PR TITLE
Feature/single threadpool

### PR DESCRIPTION
**Pull request by oddshocks**
It seems that we're running out of endpoints on the fedimg01 machines. @ralphbean, does this make sense?

### CODE REVIEW

**Comment by oddshocks** [comment]
Oh -- one more thing. A consumer test fails because I need to update what `upload()` should be called with. Whereas before it just took a list, now it needs to take some `ThreadPool` and a list. What's the best way with mock/unittest to say "any ThreadPool"?

**Comment by ralphbean** [comment]
The code as written makes sense, but I'm not sure what to suggest about the mock/test issue.

Can you show these two here?

- the traceback
- a link to the test that fails

**Comment by oddshocks** [comment]
Test: https://github.com/fedora-infra/fedimg/blob/develop/tests/test_consumers.py#L78
Traceback:
```
(fedimg) % nosetests                                                                            Repos/fedimg (feature/single-threadpool) rosemary
....F...
======================================================================
FAIL: test_send_to_uploader (test_consumers.TestKojiConsumer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/home/oddshocks/Repos/fedimg/tests/test_consumers.py", line 78, in test_send_to_uploader
    upload.assert_called_with([url1])
  File "/usr/lib/python2.7/site-packages/mock.py", line 835, in assert_called_with
    raise AssertionError(msg)
AssertionError: Expected call: upload(['https://kojipkgs.fedoraproject.org//work/tasks/7981/7577981/fedora-cloud-base-20140915-21.x86_64.raw.xz'])
Actual call: upload(<multiprocessing.pool.ThreadPool object at 0x7f8fb4158510>, ['https://kojipkgs.fedoraproject.org//work/tasks/7981/7577981/fedora-cloud-base-20140915-21.x86_64.raw.xz'])
-------------------- >> begin captured logging << --------------------
fedmsg: DEBUG: kojiconsumer is True
fedmsg: INFO:   enabled by config  - fedimg.consumers:KojiConsumer
moksha.hub: DEBUG: Subscribing to consumer topic org.fedoraproject.prod.buildsys.task.state.change
fedmsg: INFO: No backlog handling.  status: None, url: None
fedmsg: INFO: Super happy fedimg ready and reporting for duty.
fedmsg: INFO: Received 'org.fedoraproject.prod.buildsys.task.state.change' 1
fedmsg: INFO: Got Koji build 7577982
fedmsg: INFO: Got Koji build 7577981
fedmsg: INFO: Image https://kojipkgs.fedoraproject.org//work/tasks/7981/7577981/fedora-cloud-base-20140915-21.x86_64.raw.xz will be uploaded
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 8 tests in 4.745s

FAILED (failures=1)
```

**Comment by ralphbean** [comment]
Ah, you can probably use [mock.ANY](http://www.voidspace.org.uk/python/mock/helpers.html#mock.ANY) here.

**Comment by oddshocks** [comment]
That does it. Good to merge and see if it fixes things in staging?

**Comment by ralphbean** [comment]
Yeah.  :+1:

Have you considered setting up travis-ci for fedimg?  Then we could all see the tests passing or not here in the PR.  :)

**Comment by oddshocks** [comment]
:+1: I'll add that to my list

**Pull request merged**
