### PR TITLE
 Dropped 'os' and 'ver' from the AWS_AMIS config

### LINKED ISSUE #38: Drop 'os' and 'ver' from the AWS_AMIS config
The config has a list of regions to upload to, which is called AWS_AMIs internally.  It is a pipe-delimited list of regions with corresponding AMIs.  For unknown reasons, each row contains an 'os' entry and a 'ver' entry (for example 'RHEL' and '6.5').  From what I can tell, they are not used.  Can they just be removed?

### PR DESCRIPTION
**Pull request by nishant-mor**
Closed #38

### CODE REVIEW

**Comment by ralphbean** [comment]
Heh, can we drop them from the config file and everything too?  The code after this patch will assume that ``attrs[1]`` and ``attrs[2]`` are still there.

Maybe add some detection logic in there:

```python
if the file format is the old way:
    extract the values in the old way, assuming the values are there.
else if the file format is the new way:
    extract the values in the new way, assuming the values are not there
```

We'll need something like this, simply so we can upgrade our production config file.

**Comment by nishant-mor** [comment]
sir, is it ok now ?

**Comment by ralphbean** [comment]
I think so.  @sayanchowdhury, @kushaldas, can one of you review and handle this one?

**Comment by sayanchowdhury** [comment]
LGTM :+1:

**Comment by nishant-mor** [comment]
Now what is the next procedure?

**Comment by ralphbean** [comment]
@sayanchowdhury can merge it.  :)

**Pull request merged**
