### PR TITLE
consumers: Fix the metadata handling for Rawhide messages

### PR DESCRIPTION
**Pull request by sayanchowdhury**
Signed-off-by: Sayan Chowdhury <sayan.chowdhury2012@gmail.com>

### CODE REVIEW

**Comment by sayanchowdhury** [comment]
This also fixes #98

**Comment by dustymabe** [comment]
> This also fixes #98

there is no way this fixes #98 because that code gets executed before this code that is being deleted. Opened #104 to fix #98.

**Comment by dustymabe** [comment]
The code here LGTM.

**Comment by sayanchowdhury** [comment]
Sorry, you are correct. I added it in the hotfix I sent over the mailing list for forgot to include it here. Thanks for sending the PR.

**Pull request merged**
