### PR TITLE
Fix to include nightly atomic uploads

### PR DESCRIPTION
**Pull request by sayanchowdhury**

### CODE REVIEW

**Comment by pypingou** [comment]
Looks sane to me but I do not know all the ins and outs of the project

**Comment by ralphbean** [comment]
There's got to be better commenting here @sayanchowdhury.

- Can you explain why this will start including nightly atomic uploads?  I have no idea.
- Can you add that explanation to the git commit message, or as an inline comment in the code.  If someone comes along to find this a few years from now, they won't know why the change was made.

**Comment by sayanchowdhury** [comment]
@ralphbean I have edited and added comments in the git commit message itself. Have a look at it now.

**Comment by ralphbean** [comment]
:+1: to merge.  thanks!  :)

**Pull request merged**
